### PR TITLE
Fix keywords and types

### PR DESCRIPTION
**Pull request by dgehlich**
Hello again,

I fixed some of the keywords and types:
* INDEX ON: the ON was painted as index name
```
CREATE INDEX named_index ON scma.some_table (col_1);
CREATE INDEX ON scma.some_table (col_1);
```
* RECORD is not a keyword but a type
```
CREATE OR REPLACE FUNCTION some_function() RETURNS record AS $$
  DECLARE
    var record;
  BEGIN
END $$ LANGUAGE plpgsql;
```
* true, false, null are not keywords nor types.
but is and not words are (see below)
```
SELECT
  true, false, null,
  col_1 is null, isnull, is not null, notnull, is true, is not true, is false, is not false
;

CREATE TABLE (
  col_1 int NOT NULL
);
```
* added keywords: parallel (unsafe|restricted|safe); leakproof
* fixed types:  time(<precision value>); timestamp(<precision value>)
This one was tricky, because i had to swap the order the keyword elements `storage.type.pgsql` with `keyword.other.pgsql`.
```
CREATE OR REPLACE FUNCTION other_function() RETURNS record AS $$
  DECLARE
    time with time zone;
    timestamp without time zone;
    time(0);
    timestamp(0);
    time(0) with time zone;
    time(0) without time zone;
END $$ LANGUAGE plpgsql;
```

grafik

### CODE REVIEW

**Comment by dgehlich** [comment]
added keyword: filter for aggregate expressions
```
SELECT
  array_agg(col_1) FILTER (WHERE col2),
  array_agg(col_1) FILTER (WHERE NOT col2)
FROM some_table;
```

grafik

**Comment by tkopets** [comment]
Thanks, Dominik!

This PR has lots of nice additions, thank you for your time spent working on this.

All looks fine, except that I strongly believe that all of the `null`, `true`, `false` should be in keywords or another similar category (even though they may not be technically a keyword).
So a user can easily spot a misspelled `ture` instead of `true`.

**Comment by dgehlich** [comment]
Seems plausible. We devs had this discussion here too.

I added true, false, null as language constants
This seems the common type regarding https://macromates.com/manual/en/language_grammars#language_rules

added also the keyword reverse for reverse loops

**Comment by dgehlich** [comment]
```
SELECT true, null::numeric, 5, 5.5, 'string'
  FROM tab
    JOIN tab2 ON true
```

grafik

**Comment by tkopets** [comment]
Looks awesome!

**Pull request merged**
